---
- hosts: ctm9021l
  tasks:
  - name: inicia EM Server
    command: /usr/bin/su - emuser -c "start_all -U emuser -P AppDemo2023"
    register: result_valid
  - debug: var=result_valid.stdout_lines
