---
- hosts: ctm9021l
  tasks:
  - name: Detiene Config Agent EM
    command: /usr/bin/su cmemuser -c "em ctl -mcs -C Config_Agent -M ctm9021l -cmd shutdown"
    register: result_valid
  - debug: var=result_valid.stdout_lines
  - name: Detiene EM Server
    command: /usr/bin/su cmemuser -c "stop_server -U emuser -P Demo2023" 
    register: result_valid
  - debug: var=result_valid.stdout_lines
